require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DonationsController do

  def mock_donation(stubs={})
    @mock_donation ||= mock_model(Donation, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all donations as @donations" do
      Donation.stub(:all) { [mock_donation] }
      get :index
      assigns(:donations).should eq([mock_donation])
    end
  end

  describe "GET show" do
    it "assigns the requested donation as @donation" do
      Donation.stub(:find).with("37") { mock_donation }
      get :show, :id => "37"
      assigns(:donation).should be(mock_donation)
    end
  end

  describe "GET new" do
    it "assigns a new donation as @donation" do
      Donation.stub(:new) { mock_donation }
      get :new
      assigns(:donation).should be(mock_donation)
    end
  end

  describe "GET edit" do
    it "assigns the requested donation as @donation" do
      Donation.stub(:find).with("37") { mock_donation }
      get :edit, :id => "37"
      assigns(:donation).should be(mock_donation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created donation as @donation" do
        Donation.stub(:new).with({'these' => 'params'}) { mock_donation(:save => true) }
        post :create, :donation => {'these' => 'params'}
        assigns(:donation).should be(mock_donation)
      end

      it "redirects to the created donation" do
        Donation.stub(:new) { mock_donation(:save => true) }
        post :create, :donation => {}
        response.should redirect_to(donation_url(mock_donation))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved donation as @donation" do
        Donation.stub(:new).with({'these' => 'params'}) { mock_donation(:save => false) }
        post :create, :donation => {'these' => 'params'}
        assigns(:donation).should be(mock_donation)
      end

      it "re-renders the 'new' template" do
        Donation.stub(:new) { mock_donation(:save => false) }
        post :create, :donation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested donation" do
        Donation.stub(:find).with("37") { mock_donation }
        mock_donation.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :donation => {'these' => 'params'}
      end

      it "assigns the requested donation as @donation" do
        Donation.stub(:find) { mock_donation(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:donation).should be(mock_donation)
      end

      it "redirects to the donation" do
        Donation.stub(:find) { mock_donation(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(donation_url(mock_donation))
      end
    end

    describe "with invalid params" do
      it "assigns the donation as @donation" do
        Donation.stub(:find) { mock_donation(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:donation).should be(mock_donation)
      end

      it "re-renders the 'edit' template" do
        Donation.stub(:find) { mock_donation(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested donation" do
      Donation.stub(:find).with("37") { mock_donation }
      mock_donation.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the donations list" do
      Donation.stub(:find) { mock_donation }
      delete :destroy, :id => "1"
      response.should redirect_to(donations_url)
    end
  end

end
